services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    depends_on:
      - postgres
    build: .
    environment:
      - DB_URI=${DB_URI}
    restart: unless-stopped

volumes:
  postgres_data:
